version: '3.3'
services:
  java-maven-app:
    image: iamkhaihoang/demo-app:1.0.1
    ports:
      - 8080:8080
  postgres:
    image: postgres:13
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=my-pwd